In [1]:
import os
import pandas as pd

In [2]:
os.chdir("E:/DataScience/")

In [3]:
csv_file=pd.read_csv("c_data.csv",header=2)
csv_file

1  CountryName CountryCode  Population growth  Total population  \
0    2       Brazil         BRA           0.817556      2.076529e+08   
1    3  Switzerland         CHE           1.077221      8.372098e+06   
2    4      Germany         DEU           1.193867      8.266768e+07   
3    5      Denmark         DNK           0.834638               NaN   
4    6        Spain         ESP          -0.008048      4.644396e+07   
5    7       France         FRA           0.407491      6.689611e+07   
6    8        Japan         JPN          -0.115284      1.269945e+08   
7    9       Greece         GRC          -0.687543      1.074674e+07   
8   10         Iran         IRN           1.148789      8.027743e+07   
9   11       Kuwait         KWT           2.924206      4.052584e+06   
10  12      Morocco         MAR                NaN      3.527679e+07   
11  13      Nigeria         NGA           2.619034      1.859896e+08   
12  14        Qatar         QAT           3.495070      2.569804e+06   
13  15       Sweden         SWE                NaN      9.903122e+06   
14  16        India         IND           1.148215      1.324171e+09   
15  17        World         WLD           1.181680      7.442136e+09   

    Area (sq. km)  
0       8358140.0  
1         39516.0  
2        348900.0  
3         42262.0  
4        500210.0  
5        547557.0  
6        364560.0  
7        128900.0  
8       1628760.0  
9             NaN  
10       446300.0  
11       910770.0  
12        11610.0  
13       407310.0  
14      2973190.0  
15    129733172.7

In [4]:
csv_file.drop("1",axis=1,inplace=True)

In [5]:
csv_file

CountryName CountryCode  Population growth  Total population  \
0        Brazil         BRA           0.817556      2.076529e+08   
1   Switzerland         CHE           1.077221      8.372098e+06   
2       Germany         DEU           1.193867      8.266768e+07   
3       Denmark         DNK           0.834638               NaN   
4         Spain         ESP          -0.008048      4.644396e+07   
5        France         FRA           0.407491      6.689611e+07   
6         Japan         JPN          -0.115284      1.269945e+08   
7        Greece         GRC          -0.687543      1.074674e+07   
8          Iran         IRN           1.148789      8.027743e+07   
9        Kuwait         KWT           2.924206      4.052584e+06   
10      Morocco         MAR                NaN      3.527679e+07   
11      Nigeria         NGA           2.619034      1.859896e+08   
12        Qatar         QAT           3.495070      2.569804e+06   
13       Sweden         SWE                NaN      9.903122e+06   
14        India         IND           1.148215      1.324171e+09   
15        World         WLD           1.181680      7.442136e+09   

    Area (sq. km)  
0       8358140.0  
1         39516.0  
2        348900.0  
3         42262.0  
4        500210.0  
5        547557.0  
6        364560.0  
7        128900.0  
8       1628760.0  
9             NaN  
10       446300.0  
11       910770.0  
12        11610.0  
13       407310.0  
14      2973190.0  
15    129733172.7

In [6]:
csv_file.describe()

Population growth  Total population  Area (sq. km)
count          14.000000      1.500000e+01   1.500000e+01
mean            1.145492      6.422767e+08   9.762744e+06
std             1.173195      1.909868e+09   3.325701e+07
min            -0.687543      2.569804e+06   1.161000e+04
25%             0.510007      1.032493e+07   2.389000e+05
50%             1.112718      6.689611e+07   4.463000e+05
75%             1.190820      1.564921e+08   1.269765e+06
max             3.495070      7.442136e+09   1.297332e+08

In [7]:
csv_file.isnull().values.sum()

4

In [18]:
csv_file.isnull().values

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [19]:
import numpy as np
file=np.array(csv_file.values)
file

array([['Brazil', 'BRA', 0.8175557109999999, 207652865.0, 8358140.0],
       ['Switzerland', 'CHE', 1.077221168, 8372098.0, 39516.0],
       ['Germany', 'DEU', 1.193866758, 82667685.0, 348900.0],
       ['Denmark', 'DNK', 0.8346376109999999, nan, 42262.0],
       ['Spain', 'ESP', -0.008048086, 46443959.0, 500210.0],
       ['France', 'FRA', 0.40749103600000003, 66896109.0, 547557.0],
       ['Japan', 'JPN', -0.11528417699999999, 126994511.0, 364560.0],
       ['Greece', 'GRC', -0.687542545, 10746740.0, 128900.0],
       ['Iran', 'IRN', 1.1487886, 80277428.0, 1628760.0],
       ['Kuwait', 'KWT', 2.924206194, 4052584.0, nan],
       ['Morocco', 'MAR', nan, 35276786.0, 446300.0],
       ['Nigeria', 'NGA', 2.619033526, 185989640.0, 910770.0],
       ['Qatar', 'QAT', 3.495069918, 2569804.0, 11610.0],
       ['Sweden', 'SWE', nan, 9903122.0, 407310.0],
       ['India', 'IND', 1.148214693, 1324171354.0, 2973190.0],
       ['World', 'WLD', 1.18167997, 7442135578.0, 129733172.7]],
      dtype=o

In [20]:
from sklearn.preprocessing import Imputer
imp=Imputer(missing_values="NaN",strategy="mean",axis=0)
imp.fit(file[:,2:])
file[:,2:]=imp.transform(file[:,2:])


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [21]:
file

array([['Brazil', 'BRA', 0.8175557109999999, 207652865.0, 8358140.0],
       ['Switzerland', 'CHE', 1.077221168, 8372098.0, 39516.0],
       ['Germany', 'DEU', 1.193866758, 82667685.0, 348900.0],
       ['Denmark', 'DNK', 0.8346376109999999, 642276684.2, 42262.0],
       ['Spain', 'ESP', -0.008048086, 46443959.0, 500210.0],
       ['France', 'FRA', 0.40749103600000003, 66896109.0, 547557.0],
       ['Japan', 'JPN', -0.11528417699999999, 126994511.0, 364560.0],
       ['Greece', 'GRC', -0.687542545, 10746740.0, 128900.0],
       ['Iran', 'IRN', 1.1487886, 80277428.0, 1628760.0],
       ['Kuwait', 'KWT', 2.924206194, 4052584.0, 9762743.846666666],
       ['Morocco', 'MAR', 1.145492169785714, 35276786.0, 446300.0],
       ['Nigeria', 'NGA', 2.619033526, 185989640.0, 910770.0],
       ['Qatar', 'QAT', 3.495069918, 2569804.0, 11610.0],
       ['Sweden', 'SWE', 1.145492169785714, 9903122.0, 407310.0],
       ['India', 'IND', 1.148214693, 1324171354.0, 2973190.0],
       ['World', 'WLD', 1.18

In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
ct=ColumnTransformer(transformers=[("encoder",OrdinalEncoder(),[0,1])],remainder="passthrough")
file_end=np.array(ct.fit_transform(file))

In [30]:
print(file_end)

[[0.0 0.0 0.8175557109999999 207652865.0 8358140.0]
 [14.0 1.0 1.077221168 8372098.0 39516.0]
 [3.0 2.0 1.193866758 82667685.0 348900.0]
 [1.0 3.0 0.8346376109999999 642276684.2 42262.0]
 [12.0 4.0 -0.008048086 46443959.0 500210.0]
 [2.0 5.0 0.40749103600000003 66896109.0 547557.0]
 [7.0 9.0 -0.11528417699999999 126994511.0 364560.0]
 [4.0 6.0 -0.687542545 10746740.0 128900.0]
 [6.0 8.0 1.1487886 80277428.0 1628760.0]
 [8.0 10.0 2.924206194 4052584.0 9762743.846666666]
 [9.0 11.0 1.145492169785714 35276786.0 446300.0]
 [10.0 12.0 2.619033526 185989640.0 910770.0]
 [11.0 13.0 3.495069918 2569804.0 11610.0]
 [13.0 14.0 1.145492169785714 9903122.0 407310.0]
 [5.0 7.0 1.148214693 1324171354.0 2973190.0]
 [15.0 15.0 1.18167997 7442135578.0 129733172.7]]


In [34]:
new=pd.DataFrame(file_end,index=csv_file.index,columns=csv_file.columns)

In [35]:
new

CountryName CountryCode Population growth Total population Area (sq. km)
0             0           0          0.817556      2.07653e+08   8.35814e+06
1            14           1           1.07722       8.3721e+06         39516
2             3           2           1.19387      8.26677e+07        348900
3             1           3          0.834638      6.42277e+08         42262
4            12           4       -0.00804809       4.6444e+07        500210
5             2           5          0.407491      6.68961e+07        547557
6             7           9         -0.115284      1.26995e+08        364560
7             4           6         -0.687543      1.07467e+07        128900
8             6           8           1.14879      8.02774e+07   1.62876e+06
9             8          10           2.92421      4.05258e+06   9.76274e+06
10            9          11           1.14549      3.52768e+07        446300
11           10          12           2.61903       1.8599e+08        910770
12           11          13           3.49507       2.5698e+06         11610
13           13          14           1.14549      9.90312e+06        407310
14            5           7           1.14821      1.32417e+09   2.97319e+06
15           15          15           1.18168      7.44214e+09   1.29733e+08